
name: Perl package

on:
  push:
    branches: [ '*' ]
    tags-ignore: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  perl:
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        perl-version: ['5.20', '5.32', 'latest', 'threaded']
    container:
      image: perl:${{ matrix.perl-version }}

    steps:
    - uses: actions/checkout@v2
    - name: perl -V
      run: perl -V
    - name: Install Dependencies
      run: curl -sL https://git.io/cpm | perl - install -g --show-build-log-on-failure
    - name: Install Dev Dependencies
      run: curl -sL https://git.io/cpm | perl - install Module::Build::Tiny -g --show-build-log-on-failure
    - name: Test
      run: |
        perl ./Build.PL ; ./Build ; ./Build test
